manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: paulshir
      url-base: https://github.com/paulshir
    - name: urob
      url-base: https://github.com/urob
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
    - name: zmk
      remote: paulshir
    #  revision: split-serial-pr+pio-led
      revision: paulshir
      import: app/west.yml
    - name: zmk-board-iris-ce
      remote: paulshir
      revision: main
    - name: zmk-behaviors-dev
      remote: paulshir
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
  self:
    path: config
